CREATE TABLE MY_EMPLOYEE (
    EMPNO NUMBER(4),
    ENAME VARCHAR2(50),
    DEPTNO NUMBER(2),
    SAL NUMBER(10,2)
);

INSERT INTO MY_EMPLOYEE VALUES (101, 'Rahul', 10, 30000);
INSERT INTO MY_EMPLOYEE VALUES (102, 'Priya', 20, 40000);
INSERT INTO MY_EMPLOYEE VALUES (103, 'Aman', 30, 35000);

DECLARE
    v_data MY_EMPLOYEE%ROWTYPE;
BEGIN
    SELECT *
    INTO v_data
    FROM MY_EMPLOYEE
    WHERE EMPNO = 102;

    DBMS_OUTPUT.PUT_LINE(v_data.ENAME || ' ' || v_data.SAL);
END;
/
